##########################################################################################
#
# This is for DEVELOPMENT purposes. We deploy using similar configuration but using dokku.
#
##########################################################################################

version: '3'

services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=budgetportal
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=budgetportal
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: python manage.py runserver_plus --nopin 0.0.0.0:8000
    environment:
      - TAG_MANAGER_ID
      - DATABASE_URL=postgresql://budgetportal:devpassword@db/budgetportal
      - DJANGO_DEBUG_TOOLBAR
      - AWS_ACCESS_KEY_ID=minio-access-key
      - AWS_SECRET_ACCESS_KEY=minio-secret-key
      - AWS_STORAGE_BUCKET_NAME=budgetportal-storage
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_SECURE_URLS=True
      - AWS_S3_CUSTOM_DOMAIN
      - SOLR_URL=http://solr:8983/solr/budgetportal
      - DEBUG_CACHE
      - DJANGO_WHITENOISE_AUTOREFRESH=TRUE
      - CKAN_URL
      - OPEN_SPENDING_USER_ID=616cdf6f2657070da7d2fa056df55206
      - OPEN_SPENDING_BASE_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyaWQiOiI2MTZjZGY2ZjI2NTcwNzBkYTdkMmZhMDU2ZGY1NTIwNiIsInBlcm1pc3Npb25zIjp7ImRhdGFwYWNrYWdlLXVwbG9hZCI6dHJ1ZX0sInNlcnZpY2UiOiJvcy5kYXRhc3RvcmUifQ.RX6R0DhPSzFokZXZEKnln2MkllmCEHBpQuyEPK3MWgVwxWy3jsBJov20HveRK1K0pm8VH-0sHoM9faTlYa04m8ZtEAGUWiGg5WrpkFmKRiiQjmVPkHy9FNIV3DBnPPHPZ-OuIYGa-AuV_hnX5valV5R6FjRv6_4wgGEVl7bIIxki0g-4pA1Qv2a7cy4_oqo6zSrpSkU-75e49ytkVPjhzqX8WaMQ2pnbeILtFN6di8EHV7_ls5QJzLJiYNsbH48iijbA9HcjLFSX_CYUoDFbXI_SuIs4CbxEWGPs-ZdaN0GeQLMNblLzpzCD2-Vrl3X3wQUGks8rDxbJvTaW7QNTMg
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - solr
      - minio-client
      - minio

  # Should be same as app except for command and ports
  worker:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: python manage.py qcluster
    environment:
      - DATABASE_URL=postgresql://budgetportal:devpassword@db/budgetportal
      - DJANGO_DEBUG_TOOLBAR=${DJANGO_DEBUG_TOOLBAR}
      - AWS_ACCESS_KEY_ID=minio-access-key
      - AWS_SECRET_ACCESS_KEY=minio-secret-key
      - AWS_STORAGE_BUCKET_NAME=budgetportal-storage
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - SOLR_URL=http://solr:8983/solr/budgetportal
      - CKAN_URL
      - OPEN_SPENDING_USER_ID=616cdf6f2657070da7d2fa056df55206
      - OPEN_SPENDING_BASE_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyaWQiOiI2MTZjZGY2ZjI2NTcwNzBkYTdkMmZhMDU2ZGY1NTIwNiIsInBlcm1pc3Npb25zIjp7ImRhdGFwYWNrYWdlLXVwbG9hZCI6dHJ1ZX0sInNlcnZpY2UiOiJvcy5kYXRhc3RvcmUifQ.RX6R0DhPSzFokZXZEKnln2MkllmCEHBpQuyEPK3MWgVwxWy3jsBJov20HveRK1K0pm8VH-0sHoM9faTlYa04m8ZtEAGUWiGg5WrpkFmKRiiQjmVPkHy9FNIV3DBnPPHPZ-OuIYGa-AuV_hnX5valV5R6FjRv6_4wgGEVl7bIIxki0g-4pA1Qv2a7cy4_oqo6zSrpSkU-75e49ytkVPjhzqX8WaMQ2pnbeILtFN6di8EHV7_ls5QJzLJiYNsbH48iijbA9HcjLFSX_CYUoDFbXI_SuIs4CbxEWGPs-ZdaN0GeQLMNblLzpzCD2-Vrl3X3wQUGks8rDxbJvTaW7QNTMg
    volumes:
      - .:/code
    depends_on:
      - db
      - solr
      - minio

  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    command: bin/wait-for-db.sh python manage.py test
    environment:
      - DATABASE_URL=postgresql://budgetportal:devpassword@db/budgetportal
      - AWS_ACCESS_KEY_ID=minio-access-key
      - AWS_SECRET_ACCESS_KEY=minio-secret-key
      - AWS_STORAGE_BUCKET_NAME=budgetportal-storage
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_SECURE_URLS=True
      - SOLR_URL=http://solr:8983/solr/budgetportal-test
      - DJANGO_Q_SYNC=TRUE
    volumes:
      - .:/code
    depends_on:
      - db
      - solr
      - minio

  minio:
    image: "minio/minio:RELEASE.2019-10-12T01-39-57Z"
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
      - MINIO_DOMAIN=minio
    command: minio --compat server data

  minio-client:
    image: "minio/mc"
    depends_on:
      - minio
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
      - MINIO_DOMAIN=minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc mb budgetportal-storage;
      /usr/bin/mc policy set public budgetportal-storage;
      "

  solr:
    build: "https://github.com/vulekamali/solr-dokku.git"
    image: budgetportal-solr
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/opt/solr/server/solr/budgetportal/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536



volumes:
  db-data:
  minio-data:
  solr-data:
